### PR TITLE
TRITON-2130 Add snapshot-limit to VMAPI

### PR DESCRIPTION
**Pull request by danmcd**

### CODE REVIEW

**Comment by danmcd** [comment]
Like this?

```
diff --git a/package.json b/package.json
index cf7480a..1494c65 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
     "name": "vm-agent",
     "description": "SmartDC Node VM Agent",
-    "version": "1.8.3",
+    "version": "1.8.4",
     "author": "Joyent (joyent.com)",
     "private": true,
     "dependencies": {
```

**Comment by twhiteman** [comment]
Yep - looks good.

**Comment by danmcd** [comment]
Can this change be pushed independently of the VMAPI one?

**Comment by twhiteman** [comment]
Yes - this is ready to go.

**Pull request merged**
