### PR TITLE
set zone_state for destroyed VMs

### PR DESCRIPTION
**Pull request by misterdjules**

### CODE REVIEW

**Comment by misterdjules** [comment]
This change is needed by https://github.com/joyent/sdc-vmapi/pull/11.

**Comment by trentm** [comment]
If we want to have a vm-agent ver on which VMAPI upgrade depends, then we should definitely get a package.json#version bump for vm-agent with this change, please.

**Comment by misterdjules** [comment]
@trentm Bumped the minor version of vm-agent and [added an `sdcDependencies` entry for vm-agent in VMAPI](https://github.com/joyent/sdc-vmapi/pull/11/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34).

**Comment by trentm** [comment]
@misterdjules Make sure the commit message has the ticket number, then LGTM.

**Comment by misterdjules** [comment]
@trentm Done, thank you!

**Comment by misterdjules** [comment]
Closing as I won't be working on that and I don't think there's any interest in getting that merged.

**Pull request closed without merging**
